#!/bin/bash -e

tvd_name=$1; shift

hub clone -p $tvd_name ../$tvd_name --recursive

cd ../$tvd_name

git remote add tvdinner "https://github.com/HeSYINUvSBZfxqA/tvdinner"
git fetch tvdinner
git merge tvdinner/master
git submodule update --init --recursive
exec bash -i -l
