#!/bin/bash -e

if [[ ! -f "features/Gemfile.lock" ]]; then
  cp "features/Gemfile.lock.template" "features/Gemfile.lock"
  cd features
  bundle update --local $(basename $(dirname $(pwd))) 
  cd -
fi

cd features
bundle check || { bundle install --local && bundle check; }
cd -

BUNDLE_GEMFILE=$(pwd)/features/Gemfile bundle exec cucumber "$@"
