#!/bin/bash -e

if [[ ! -f "oijangajji/Gemfile.lock" ]]; then
  cd oijangajji
  cp Gemfile.lock.template Gemfile.lock
  bundle update --local $(basename $(dirname $(pwd))) 
  cd -
fi

cd oijangajji
bundle check || { bundle install --local && bundle check; }
cd -

BUNDLE_GEMFILE=$(pwd)/oijangajji/Gemfile bundle exec cucumber "$@"
